name: Solar Theme
url: https://orels1.github.io/
description: Вдохновленный Kancolle пак скинов для японских кораблей
baseurl: "/wows-kancolle"

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
